### ISSUE TITLE
运行训练代码报错

### ISSUE THREAD

**Issue by upupbo** [lidq92/MDTVSFA#10]
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
查了我的docker容器默认shm是64M，请问应该改为多少G才不会报这个错

**Comment by lidq92** [comment]
我没遇到过这个问题，也没改过shm, 我不清楚要改到多大才能不报错。
你可以自己在网上查一下，比如https://zhuanlan.zhihu.com/p/59271905这个的第5点建议你把Dataloader的num_workers设置为0，或者也可以建docker的时候加个参数 shmsize xxG 更改默认的shm内存到更大的值。
如果还不行，你可根据自己的实际情况按关键词在网上查一下解决方案，比如会出来https://blog.csdn.net/u013823233/article/details/101209718 http://ai.baidu.com/forum/topic/show/957544之类的。

这种问题只跟你的机器使用pytorch训练的时候有关，跟具体的代码没关系，可以去看pytorch官方的解释。
