### ISSUE TITLE
网络模型很难迁移

### ISSUE THREAD

**Issue by upupbo** [lidq92/MDTVSFA#12]
我只想训练konvid-1k,但是你们的网络里面有个key，导致我必须要建立一个key

**Comment by lidq92** [comment]
我现在提供的代码可以只训练konvid-1k。我不清楚难迁移什么意思。

如果你要去掉key也是可以的，简单改一下就行了。

**Comment by upupbo** [comment]
您好，请问self.lm = nn.Sequential(OrderedDict([(dataset, nn.Linear(1, 1)) for dataset in mapping_datasets]))和
for d, dataset in enumerate(mapping_datasets):
            torch.nn.init.constant_(self.lm._modules[dataset].weight, scale[dataset])
            torch.nn.init.constant_(self.lm._modules[dataset].bias, m[dataset])
以及aligned_score[d][i] = self.lm._modules[KCL[i]](mapped_score[d][i])
如何去掉key，我们想直接用VSFA的框架运行应该怎么改，或者您可以提供一版不带key的嘛

**Comment by lidq92** [comment]
你直接在VSFA的基础上加上MDTVSFA的后面结构再换成MDTVSFA的loss就可以了。
这个改起来很简单，我相信你自己改也没问题，我有我的事情要忙，谢谢。
