### ISSUE TITLE
Consider an end-to-end network？

### ISSUE THREAD

**Issue by ciwei123** [lidq92/MDTVSFA#2]
@lidq92 Thanks for your sharing. I found that 'CNN_feature_extract' and 'regression_score' are carried out separately during the training. Have you considered an end-to-end network? That means training the ‘CNN_feature_extract’ network.  I want to know if it is necessary to train the feature extraction part.Thank you very much!!

**Comment by lidq92** [comment]
@ciwei123 It will take too many computing resources.

One possible way to update the feature extraction module is that fine-tuning it with IQA datasets.
