### ISSUE TITLE
How to extract BRISQUE features？

### ISSUE THREAD

**Issue by ciwei123** [lidq92/MDTVSFA#6]
@lidq92 Thanks for your sharing . The paper says that comparative experiment was done using BRISQUE features. How to extract BRISQUE features, using MATLAB or Python code, could you share the code with me? Thank you very much!!

**Comment by lidq92** [comment]
@ciwei123 Using the [official code](http://live.ece.utexas.edu/research/Quality/BRISQUE_release.zip) (or see [utlive/BRISQUE/MATLAB](https://github.com/utlive/BRISQUE/tree/main/MATLAB)) to extract BRISQUE features.
