### ISSUE TITLE
performance[dataset] = evaluator.state.metrics['VQA_performance']

### ISSUE THREAD

**Issue by 2279209430** [lidq92/MDTVSFA#8]
Hi Postdoc Li, why there is no key of ['VQA_performance'] in evaluator.state.metrics ？

**Comment by lidq92** [comment]
@2279209430 Please install the correct version of pytorch-ignite.
See https://github.com/lidq92/LinearityIQA/issues/3#issuecomment-734078230 for a similar discussion.

**Comment by 2279209430** [comment]
Thank you for your prompt reply !
