### ISSUE TITLE
请问您有KonVid-150k数据集的下载链接嘛

### ISSUE THREAD

**Issue by ghost** [lidq92/MDTVSFA#9]
请问您有KonVid-150k数据集的下载链接嘛

**Comment by lidq92** [comment]
@finechen9 见该数据集creator的回复 https://github.com/lidq92/VSFA/issues/38#issuecomment-875608478 （已在此回复，就不复你额外发的邮件了）

具体下载链接：
http://datasets.vqa.mmsp-kn.de/archives/k150ka.zip [mirror1](https://tori.apexcache.com/dl/FbF1nitIcoulMT-Z5zZ0Sw/1627207956/619542297/60e7516f55a6c0.18690277/k150ka.zip) [mirror2](https://www.dropbox.com/s/sebt4lg76f19olx/k150ka.zip?dl=1)
http://datasets.vqa.mmsp-kn.de/archives/k150ka_scores.csv
http://datasets.vqa.mmsp-kn.de/archives/k150ka_votes.csv
http://datasets.vqa.mmsp-kn.de/archives/k150kb.zip
http://datasets.vqa.mmsp-kn.de/archives/k150kb_scores.csv
http://datasets.vqa.mmsp-kn.de/archives/k150kb_votes.csv

**Comment by upupbo** [comment]
请问您有PatchVQ数据集的百度云盘链接或者完整的下载链接嘛

**Comment by lidq92** [comment]
@upupbo 还没有下载过，你参考作者给的readme就行吧 [baidut/PatchVQ](https://github.com/baidut/PatchVQ)

**Comment by upupbo** [comment]
学长好，请问如果要判断视频中具体每一帧的质量好坏应该用当前哪个视频质量评估或者图像质量评估数据集好

**Comment by lidq92** [comment]
类似LIVE Mobile Video Quality Database这些用了single-stimulus continuous quality evaluation (SSCQE)打分的数据集，你可以自己再调研一下。

**Comment by upupbo** [comment]
谢谢前辈

**Comment by upupbo** [comment]
前辈您好，请问您有没有发现标签中存在orig_29004122936_540_5s.mp4，但是文件夹中没有这个文件

**Comment by upupbo** [comment]
我看到标签里面k150的个数是154745，但是mp4个数是152265

**Comment by lidq92** [comment]
@upupbo 不好意思，我没用过这个数据集，你可以去咨询数据库owner，文章里写的是152265个视频。
